elastic:
    host: http://localhost
    port: 9200
    username:
    password:
    indexes:
        documents_dev_test:
            pageTitle: { type: text }
            language: { type: text }
            description: { type: text }
            content: { type: object }
        course_dev_test:
            courseName: { type: text }
            courseShortName: { type: text }
            courseDescription: { type: text }
            courseCategory: { type: text }
            courseLanguage: { type: text }
