pimcore_elastic:
    indexes:
        books:
            document:
                title: { type: keyword }
                description: { type: text }
                author: { type: object }
                publication_year: { type: date }
            filter: ''
