services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Flexibledeveloper\PimcoreElasticBundle\Services\:
        resource: '../../Services'
        exclude: '../../Services/FilterService.php'
