services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Flexibledeveloper\PimcoreElasticBundle\Services\:
        resource: '../../Services'
        exclude: '../../Services/FilterService.php'

    Flexibledeveloper\PimcoreElasticBundle\EventSubscriber\:
        resource: "../../EventSubscriber"

    Flexibledeveloper\PimcoreElasticBundle\Normalizer\:
        resource: "../../Normalizer"
